<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Ulid" Version="1.4.1" />
    <ProjectReference Include="..\..\src\SquirrelBox\SquirrelBox.csproj" />
    <ProjectReference Include="..\..\src\SquirrelBox.InMemory\SquirrelBox.InMemory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
