namespace SquirrelBox;

/// <summary>
/// Describes how a SquirrelBox metadata value was resolved.
/// </summary>
public enum SquirrelBoxMetadataValueSource
{
    /// <summary>
    /// No value was available.
    /// </summary>
    Missing,

    /// <summary>
    /// The value came from incoming transport metadata.
    /// </summary>
    Incoming,

    /// <summary>
    /// The value was generated by SquirrelBox.
    /// </summary>
    Generated,

    /// <summary>
    /// The value was computed from the semantic payload hash.
    /// </summary>
    ComputedFromPayload,

    /// <summary>
    /// The value came from a broker message id.
    /// </summary>
    BrokerMessageId,

    /// <summary>
    /// The value was restored from an existing inbox entry.
    /// </summary>
    ExistingInboxEntry,

    /// <summary>
    /// The value came from the current distributed tracing activity.
    /// </summary>
    Activity
}
